export const WELCOME_MESSAGE = "WELCOME TO YOUR TODO APP"
export const SIGNIN_OR_SIGNUP = "Please signin or signp to continue"
export const SIGNIN = "Signin"
export const SIGNUP = "Signup"
export const OR = "OR"